### ISSUE TITLE
Clash of Clans v15.83.x "chr_" files cannot be decompressed

### ISSUE THREAD

**Issue by E12Dragon** [Vorono4ka/sc-compression#1]
Hello,

With Clash of Clans v15.83.x characters.sc and characters_tex.sc has basically been made redundant as each character's sprites now have their own .sc file beginning with "chr\_". These files do not have "\_tex" pairs, which may be why the decompressor doesn't work with these. Oddly, the Valkyrie __does__ have a "\_tex" pair despite starting in "chr\_", and both the .sc and \_tex.sc files for the valkyrie do work the decompressor. A fix for this would be greatly appreciated for the rest!

I've added some samples here: [https://drive.google.com/drive/folders/1DoI658qO1XSmaPj_sTaVdAR-uULeSdoq](url)

**Comment by Vorono4ka** [comment]
Mine module uses the [pylzham](https://pypi.org/project/pylzham/) module. It's doesn't work with Python >=3.10. Watch out for the [issue](https://github.com/Galaxy1036/pylzham/issues/5). You may downgrade your python version. Or if you're using Windows, you may uninstall pylzham module to use the module built-in LZHAM codec. Thank you for the issue.

**Comment by E12Dragon** [comment]
Thanks for the response. I've downgraded to python 3.9.1, but it still cannot decompress the chr\_ files. I tested with "chr_ram_rider.sc". I also re-downloaded and used sc-compression-0.6.1. Result:
`File: ".../examples/decompressor/main.py", line 17, in <module> f.write(decompress(file_data)[0])`
`TypeError: a bytes-like object is required, not 'NoneType'`

**Comment by Vorono4ka** [comment]
This works for me after the update. 

Python 3.10. Earlier I uninstalled the `pylzham` module.
![image](https://user-images.githubusercontent.com/54549682/208416382-a5824d41-fe3b-440f-8216-9db96290cc77.png)
